# Exported from Render on 2026-03-24T03:20:46Z
version: "1"
services:
- type: web
  name: deep-sea-stakes
  runtime: node
  repo: https://github.com/CJPCJP1973/deep-sea-stakes
  plan: free
  region: virginia
  buildCommand: bun run install
  startCommand: vite preview
  autoDeployTrigger: commit
