// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-active-sessions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_active_sessions_default = defineTool({
  name: "list_active_sessions",
  title: "List active staking sessions",
  description: "List currently open/funding staking sessions with shooter, platform, buy-in, stake available, and share price.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of sessions to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").select(
      "id, shooter_name, platform, agent_room, total_buy_in, stake_available, share_price, status, end_time, stream_url"
    ).in("status", ["funding", "active"]).order("end_time", { ascending: true }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-session-details.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_session_details_default = defineTool2({
  name: "get_session_details",
  title: "Get session details",
  description: "Return full public details for a specific active/funding staking session by id: shooter, platform, agent/room, buy-in, stake available, share price, status, end time, and stream URL.",
  inputSchema: {
    session_id: z2.string().uuid().describe("The session id (uuid) to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("sessions").select(
      "id, shooter_name, platform, agent_room, total_buy_in, stake_available, share_price, status, end_time, stream_url, created_at"
    ).eq("id", session_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Session not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/tools/list-slot-pools.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_slot_pools_default = defineTool3({
  name: "list_slot_pools",
  title: "List slot pools",
  description: "List available slot pools with platform, buy-in, seats sold vs total, seat price, and end time.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max pools to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("slot_pools").select("id, name, platform, buy_in, seats, seats_sold, seat_price, end_time, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pools: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_leaderboard_default = defineTool4({
  name: "get_leaderboard",
  title: "Get shooter leaderboard",
  description: "Return the top shooters by public performance metrics.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Max entries (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.rpc("get_leaderboard", {
      limit_count: limit ?? 10
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leaderboard: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qzlmyufkwbjqdwwadham";
var mcp_default = defineMcp({
  name: "fishkillerz-mcp",
  title: "FishKillerz MCP",
  version: "0.2.0",
  instructions: "Read-only tools for the FishKillerz staking platform. Callers must be signed in via OAuth. Use `list_active_sessions` to see open shooter sessions, `get_session_details` for full info on one session, `list_slot_pools` for community slot pools, and `get_leaderboard` for top shooters.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_active_sessions_default, get_session_details_default, list_slot_pools_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
